apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-0
sepc:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclainPolicy: Retain
  mountOptions:
  - nfsvers=4.1
  nfs:
    path: web-0
    server: 192.168.92.180