apiVersion: operator.tigera.io/v1
kind: Installation
metadata: Kubernetes meta/v1.ObjectMeta 
spec:
  variant: string   # One of: Calico,TigeraSecureEnterprise
  registry: string  # One of: None, Login, Consent, SelectAccount.
  imagePath: string   
  imagePrefix: string
  imagePullSecrets: string
  kubernetesProvider: string # EKS, GKE, AKS, OpenShift, DockerEnterprise ...
  cni:
    type: Calico  # One of: Calico, GKE, AmazonVPC, AzureVNET
    ipam:  
      type: Calico
  calicoNetwork: 
    linuxDataplane: string  # One of: Iptables, BPF[柏克莱封包过滤器（Berkeley Packet Filter，缩写 BPF）]     
    bgp: string   # One of: Enabled, Disabled      
    ipPools:      
      cidr: xxx.xxx.xxx.xxx/xx 
      encapsulation: IPIP   # One of: IPIP, VXLAN, IPIPCrossSubnet, VXLANCrossSubnet, None
      natOutgoing: Enabled  # One of: Enabled, Disabled 
      nodeSelector: 'all()'
      blockSize:  26     # CIDR子网大小
    mtu:  int32   # 不指定，Calico会自动探测集群的网络设置
    nodeAddressAutodetectionV4: NodeAddressAutodetection 
    nodeAddressAutodetectionV6: NodeAddressAutodetection
    hostPorts: Enabled
    multiInterfaceMode: None    
    containerIPForwarding: Disabled
  typhaAffinity: TyphaAffinity 
  controlPlaneNodeSelector: map
  controlPlaneTolerations: Kubernetes core/v1.Toleration 
  nodeMetricsPort: int32
  typhaMetricsPort: int32
  flexVolumePath: string
  nodeUpdateStrategy: Kubernetes apps/v1.DaemonSetUpdateStrategy 
  componentResources:
    componentName: string # One of: Node, Typha, KubeControllers
    resourceRequirements: Kubernetes core/v1.ResourceRequirements 
  certificateManagement:
    caCert: byte
    signerName: "<my-domain>/<my-signername>"
    keyAlgorithm: RSAWithSize2048
    signatureAlgorithm: SHA256WithRSA

